### ISSUE TITLE
Build failed in MacOS

### ISSUE THREAD

**Issue by mfbenitezp** [dabreegster/rampfs#12]
When I build cargo I got:

error: failed to run custom build command for `proj-sys v0.18.4`
Caused by:
 process didn’t exit successfully: `/Users/fbenitez/Documents/ResearchATI/EcoTwins_Rust/rampfs/target/release/build/proj-sys-913625d2b4418d78/build-script-build` (exit status: 101)
 --- stdout
 cargo:rerun-if-env-changed=PROJ_NO_PKG_CONFIG
 cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-apple-darwin
 cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_apple_darwin
 cargo:rerun-if-env-changed=HOST_PKG_CONFIG
 cargo:rerun-if-env-changed=PKG_CONFIG
 cargo:rerun-if-env-changed=PROJ_STATIC
 cargo:rerun-if-env-changed=PROJ_DYNAMIC
 cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
 cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
 cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
 cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
 cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
 cargo:rerun-if-env-changed=PKG_CONFIG_PATH
 cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
 cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
 cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
 cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
 cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
 cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
 cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
 cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
 CMAKE_TOOLCHAIN_FILE_x86_64-apple-darwin = None
 CMAKE_TOOLCHAIN_FILE_x86_64_apple_darwin = None
 HOST_CMAKE_TOOLCHAIN_FILE = None
 CMAKE_TOOLCHAIN_FILE = None
 CMAKE_GENERATOR_x86_64-apple-darwin = None
 CMAKE_GENERATOR_x86_64_apple_darwin = None
 HOST_CMAKE_GENERATOR = None
 CMAKE_GENERATOR = None
 CMAKE_PREFIX_PATH_x86_64-apple-darwin = None
 CMAKE_PREFIX_PATH_x86_64_apple_darwin = None
 HOST_CMAKE_PREFIX_PATH = None
 CMAKE_PREFIX_PATH = None
 CMAKE_x86_64-apple-darwin = None
 CMAKE_x86_64_apple_darwin = None
 HOST_CMAKE = None
 CMAKE = None
 running: “cmake” “/Users/fbenitez/.cargo/registry/src/github.com-1ecc6299db9ec823/proj-sys-0.18.4/PROJSRC/proj/proj-7.1.0" “-DBUILD_SHARED_LIBS=OFF” “-DBUILD_TESTING=OFF” “-DBUILD_CCT=OFF” “-DBUILD_CS2CS=OFF” “-DBUILD_GEOD=OFF” “-DBUILD_GIE=OFF” “-DBUILD_PROJ=OFF” “-DBUILD_PROJINFO=OFF” “-DBUILD_PROJSYNC=OFF” “-DENABLE_CURL=OFF” “-DENABLE_TIFF=OFF” “-DCMAKE_INSTALL_PREFIX=/Users/fbenitez/Documents/ResearchATI/EcoTwins_Rust/rampfs/target/release/build/proj-sys-216d9a73e00ccca2/out” “-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64” “-DCMAKE_C_COMPILER=/usr/bin/cc” “-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64” “-DCMAKE_CXX_COMPILER=/usr/bin/c++” “-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64” “-DCMAKE_ASM_COMPILER=/usr/bin/cc” “-DCMAKE_BUILD_TYPE=Release”
 --- stderr
 pkg-config unable to find existing libproj installation: Could not run `“pkg-config” “--libs” “--cflags” “proj” “proj >= 7.1.0"`
 The pkg-config command could not be found.
 Most likely, you need to install a pkg-config package for your OS.
 Try `brew install pkg-config` if you have Homebrew.
 If you’ve already installed it, ensure the pkg-config command is one of the
 directories in the PATH environment variable.
 If you did not expect this build to link to a pre-installed system library,
 then check documentation of the proj-sys crate for an option to
 build the library from source, or disable features or dependencies
 that require pkg-config.
 building libproj from source
 thread ‘main’ panicked at '
 failed to execute command: No such file or directory (os error 2)
 is `cmake` not installed?
 build script failed, must exit now’, /Users/fbenitez/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.46/src/lib.rs:974:5
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by mfbenitezp** [comment]
Then I tried: `brew install pkg-config`, but similar issue after. 

  ```
 Compiling proj-sys v0.18.4
error: failed to run custom build command for `proj-sys v0.18.4`

Caused by:
  process didn't exit successfully: `/Users/fbenitez/Documents/ResearchATI/EcoTwins_Rust/rampfs/target/release/build/proj-sys-913625d2b4418d78/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PROJ_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PROJ_STATIC
  cargo:rerun-if-env-changed=PROJ_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  CMAKE_TOOLCHAIN_FILE_x86_64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_x86_64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-apple-darwin = None
  CMAKE_GENERATOR_x86_64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-apple-darwin = None
  CMAKE_PREFIX_PATH_x86_64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-apple-darwin = None
  CMAKE_x86_64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/Users/fbenitez/.cargo/registry/src/github.com-1ecc6299db9ec823/proj-sys-0.18.4/PROJSRC/proj/proj-7.1.0" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_TESTING=OFF" "-DBUILD_CCT=OFF" "-DBUILD_CS2CS=OFF" "-DBUILD_GEOD=OFF" "-DBUILD_GIE=OFF" "-DBUILD_PROJ=OFF" "-DBUILD_PROJINFO=OFF" "-DBUILD_PROJSYNC=OFF" "-DENABLE_CURL=OFF" "-DENABLE_TIFF=OFF" "-DCMAKE_INSTALL_PREFIX=/Users/fbenitez/Documents/ResearchATI/EcoTwins_Rust/rampfs/target/release/build/proj-sys-216d9a73e00ccca2/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  pkg-config unable to find existing libproj installation: `"pkg-config" "--libs" "--cflags" "proj" "proj >= 7.1.0"` did not exit successfully: exit status: 1
  error: could not find system library 'proj' required by the 'proj-sys' crate

  --- stderr
  Package proj was not found in the pkg-config search path.
  Perhaps you should add the directory containing `proj.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'proj' found
  Package proj was not found in the pkg-config search path.
  Perhaps you should add the directory containing `proj.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'proj' found

  building libproj from source
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /Users/fbenitez/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.46/src/lib.rs:974:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dabreegster** [comment]
Try `brew install cmake` then (see the very end of that error log). After that, you might also have to do `brew install proj` or `libproj`. I did all of this on my Macbook and forgot to write it down. We can update the README with the steps once we figure it out. I don't think it should be that tough -- it was just 2 or 3 installs through brew

**Comment by mfbenitezp** [comment]
Sure. Let's see I got it right and then I update the Readme.

**Comment by mfbenitezp** [comment]
Done. The missed steps were: 

- [X] brew install cmake
- [X] brew install proj
